### ISSUE TITLE
What is the default quantification window?

### ISSUE THREAD

**Issue by Huanle** [YakhiniGroup/crispector#4]
Hi Crispector developers,

Thanks a lot for making this innovative tool available to the community.

I just started to play with it and I have a quick question regarding the setting-up of the quantification window size. I can see a relevant flag available with the `plotting` script. However, I have not found any option/flag that allows tuning this parameter in the main program. Can you tell me the default window size and give me hint on how to determine it?

Thanks a lot.
Best,
Huanle

**Comment by theAguy** [comment]
Dear Huanle,
Thank you for approaching us regarding CRISPECTOR,
We gladly help you with our tool.

The hyper-parameter you are looking for is indeed not in the main options, however, it can be changed:
Follow the path to get to the *default_config.yml* file:
crispector -> config -> default_config.yml

inside the .yml file you can change the window size as you wish.
But, make sure you fully understand all the consequences of the change.

Please let me know if there are any more questions,
Guy

**Comment by Huanle** [comment]
thanks a lot @theAguy
