### ISSUE TITLE
Assigning reads to target amplicons for treatment- killed

### ISSUE THREAD

**Issue by laurahernandez-hernandez** [YakhiniGroup/crispector#5]
* crispector version: 1.0.4
* Python version: 3.7
* Operating System: Ubuntu (64-bit)

### Description
I would like to compare WES data from two cell lines (parental and knock-out). Knock out cell has been edited by CRISPR/Cas9 resultin in a 8bp deletion in chr1. 
These cell lines have been purchased and sequenced by WES. 
The information they provided contains the region of deletion and sgRNA used.
I am trying to identify and quantify off-target effects using CRISPECTOR.

According to the log file the process was running without error until "Assigning reads to target amplicons for treatment" when it was killed.

I appreciate any suggestion.
Laura

### What I Did
crispector_main.log
2022-10-20 16:53:01,511 INFO	 fastp for treatment - Run (may take a few minutes).
Read1 before filtering:
total reads: 53700593
total bases: 8055088950
Q20 bases: 7829836709(97.2036%)
Q30 bases: 7462493608(92.6432%)

Read2 before filtering:
total reads: 53700593
total bases: 8055088950
Q20 bases: 7833759178(97.2523%)
Q30 bases: 7450846864(92.4986%)

Merged and filtered:
total reads: 25276611
total bases: 5714276030
Q20 bases: 5598215854(97.9689%)
Q30 bases: 5365226574(93.8916%)

Filtering result:
reads passed filter: 106630064
reads failed due to low quality: 676896
reads failed due to too many N: 24000
reads failed due to too short: 70226
reads with adapter trimmed: 873530
bases trimmed due to adapters: 18582184
reads corrected by overlap analysis: 3761319
bases corrected by overlap analysis: 6689193

Duplication rate: 16.468%

Insert size peak (evaluated by paired-end reads): 255

Read pairs merged: 25276611
% of original read pairs: 47.0695%
% in reads after filtering: 100%

JSON report: CRISPECTOR/crispector_output/treatment_fastp/fastp.json
HTML report: CRISPECTOR/crispector_output/treatment_fastp/fastp.html

fastp -i /home/ngs/Documents/NGS_Analysis/CRISPR_offtarget_test-tools/Replicate_Novogene/01.RawData/PTPRC_KO/PTPRC_KO_EKDN220010208-1A_HG7WGDSX3_L3_1.fq -I /home/ngs/Documents/NGS_Analysis/CRISPR_offtarget_test-tools/Replicate_Novogene/01.RawData/PTPRC_KO/PTPRC_KO_EKDN220010208-1A_HG7WGDSX3_L3_2.fq -o CRISPECTOR/crispector_output/treatment_fastp/r1_filtered_reads.fastq -O CRISPECTOR/crispector_output/treatment_fastp/r2_filtered_reads.fastq -m --merged_out CRISPECTOR/crispector_output/treatment_fastp/merged_reads.fastq -j CRISPECTOR/crispector_output/treatment_fastp/fastp.json -h CRISPECTOR/crispector_output/treatment_fastp/fastp.html --length_required 40 -w 2 --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT 
fastp v0.23.2, time used: 774 seconds
2022-10-20 17:05:56,260 INFO	 fastp for treatment - Done.
2022-10-20 17:05:56,261 INFO	 fastp for mock - Run (may take a few minutes).
Read1 before filtering:
total reads: 61654712
total bases: 9248206800
Q20 bases: 8991299524(97.2221%)
Q30 bases: 8571474009(92.6826%)

Read2 before filtering:
total reads: 61654712
total bases: 9248206800
Q20 bases: 9017954817(97.5103%)
Q30 bases: 8609836190(93.0974%)

Merged and filtered:
total reads: 26319739
total bases: 5982760548
Q20 bases: 5867009705(98.0653%)
Q30 bases: 5632269767(94.1417%)

Filtering result:
reads passed filter: 122476740
reads failed due to low quality: 738946
reads failed due to too many N: 27420
reads failed due to too short: 66318
reads with adapter trimmed: 794523
bases trimmed due to adapters: 18923060
reads corrected by overlap analysis: 3616141
bases corrected by overlap analysis: 6586510

Duplication rate: 18.6847%

Insert size peak (evaluated by paired-end reads): 251

Read pairs merged: 26319739
% of original read pairs: 42.6889%
% in reads after filtering: 100%

JSON report: CRISPECTOR/crispector_output/mock_fastp/fastp.json
HTML report: CRISPECTOR/crispector_output/mock_fastp/fastp.html

fastp -i /home/ngs/Documents/NGS_Analysis/CRISPR_offtarget_test-tools/Replicate_Novogene/01.RawData/HAP1_WT/HAP1_WT_EKDN220010209-1A_HG7WGDSX3_L3_1.fq -I /home/ngs/Documents/NGS_Analysis/CRISPR_offtarget_test-tools/Replicate_Novogene/01.RawData/HAP1_WT/HAP1_WT_EKDN220010209-1A_HG7WGDSX3_L3_2.fq -o CRISPECTOR/crispector_output/mock_fastp/r1_filtered_reads.fastq -O CRISPECTOR/crispector_output/mock_fastp/r2_filtered_reads.fastq -m --merged_out CRISPECTOR/crispector_output/mock_fastp/merged_reads.fastq -j CRISPECTOR/crispector_output/mock_fastp/fastp.json -h CRISPECTOR/crispector_output/mock_fastp/fastp.html --length_required 40 -w 2 --adapter_sequence=AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT 
fastp v0.23.2, time used: 893 seconds
2022-10-20 17:20:50,202 INFO	 fastp for mock - Done.
2022-10-20 17:30:22,643 INFO	 Assigning reads to target amplicons for treatment - Start assigning 25,206,921 reads - May take a few minutes

(it is not specified in the crispector_main.log but the terminal indicates that the process is killed at this point)

**Comment by nechamaklt11** [comment]
Hi Laura,
Thanks for contacting us. 
When a process is 'killed' without a warning, it usually means that the computer ran out of memory.
In Linux, you can verify this by running htop/top commands, which monitor the system resources in real-time.
Try to run CRISPECTOR without running any other programs at the same time. If it does not work, you should assign more RAM (by using a stronger computer / changing the settings in case of a virtual machine). 
Please let us know if you have any other questions,
Nechama
