### ISSUE TITLE
tx_reads_num error

### ISSUE THREAD

**Issue by CarstenKnutsen** [YakhiniGroup/crispector#8]
* crispector version:1.0.7
* Python version:3.7
* Operating System: Ubuntu 20.04

While trying to run my own files I get this error

2024-04-10 21:33:09,354 INFO	 Traceback (most recent call last):
  File "/home/carsten/anaconda3/envs/crispector_env/lib/python3.7/site-packages/crispector/crispector_main.py", line 90, in run
    tx_reads_num = tx_reads_d[site][FREQ].sum().astype(int)
AttributeError: 'int' object has no attribute 'astype'

The error occurs right after discarding sites due to low read number.

When I am running the test files, everything runs smoothly. I am running with default settings. Is this something with my config file or the fastqs themselves?

```

**Comment by CarstenKnutsen** [comment]
Was able to run it on my machine by removing ".astype(int)" from the ends of Lines 90,91,118 and 119. It seems like it was trying to convert an integer into an integer using a pandas column style attribute

**Comment by theAguy** [comment]
Thank you @CarstenKnutsen.
It seems like a Python dependencies version error, 
we will solve this problem in the next update of CRISPECTOR.
